### ISSUE TITLE
To differ idle and active connections.

### ISSUE THREAD

**Issue by yetanotherusernamebecausegithubisbugged** [josiasmontag/node-server-graceful-shutdown#1]
When shutting down the server or cluster worker gracefully there is a difference between active and idle connections. For example if user A requested a large file to download, I'd like to complete his request before shutting down the server and redirect all his new requests to another worker at the same time. I set up a 100ms server.socketIdleTimeout and added a 10 seconds sleep before sending a response to client and connection was dropped.
```coffeescript
module.exports.test = ->
  sleep = require 'co-sleep'
  yield sleep 10000
  @body = "<b>Test.</b>"   
```
Don't know if it is possible but it would be good to differ idle and active connections and apply a different timeouts to them.

**Comment by josiasmontag** [comment]
This should already be the case. This modules uses ``socket.setTimeout``, which  "Sets the socket to timeout after timeout milliseconds of *inactivity* on the socket." (https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback)

Did you try to run test.js and does this work for you? At the moment I do not see what is different to your test.

**Comment by yetanotherusernamebecausegithubisbugged** [comment]
Well then the test I use is incorrect. Sorry for the disturbance.
